---
version: 2
jobs:
  shell-lint:
    docker:
      - image: koalaman/shellcheck-alpine:v0.6.0
    steps:
      - checkout
      - run:
          name: Shell Linting
          command: for file in $(find . -type f \( -name "*.sh" -o -path "./bootstrap/*" \)); do shellcheck --format=gcc $file; done;
  terraform-fmt:
    docker:
      - image: hashicorp/terraform:0.11.1
    steps:
      - checkout
      - run:
          name: Check for master branch merges
          command: if [[ -n "$(git log origin/master..HEAD --merges)" ]]; then echo "master was merged into this branch, please use \"git rebase\" instead"; exit 1; fi
      - run:
          name: Did you fmt
          command: terraform fmt -write=false -check=true -diff=true

workflows:
  version: 2
  build_and_test:
    jobs:
      - shell-lint
      - terraform-fmt
