---
version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.1
    steps:
      - checkout
      - run:
          name: Check for master branch merges
          command: if [[ -n "$(git log origin/master..HEAD --merges)" ]]; then echo "master was merged into this branch, please use \"git rebase\" instead"; exit 1; fi
      - run:
          name: Did you fmt
          command: terraform fmt -write=false -check=true -diff=true
